services:
  web:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    restart: always
    depends_on:
      - php-fpm
      - db
  php-fpm:
    build: ./docker/php
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 54325:5432